package:
  name: iowarp
  version: 0.0.0

source:
  git_url: https://github.com/iowarp/iowarp-install
  git_depth: 1  

requirements:
  build:
    - python
    - setuptools
  run:
    - python
    - iowarp::jarvis_cd

files:
  - README.md
  - ./vcpkg/installed/x64-linux/
  
test:
  requires:
    - pip
  commands:
    - pip --help
  
about:
  home: https://grc.iit.edu/research/projects/iowarp/
  license: BSD
  summary: IOWarp Conda Package